# Generated by Django 4.1.7 on 2023-03-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInformationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('one_to_fivehundred', models.CharField(blank=True, default='no', max_length=5, null=True)),
                ('fivehundred_to_1000', models.CharField(blank=True, default='no', max_length=5, null=True)),
                ('one_two_thousand', models.CharField(blank=True, default='no', max_length=5, null=True)),
                ('two_four_thousand', models.CharField(blank=True, default='no', max_length=5, null=True)),
                ('more4000', models.CharField(blank=True, default='no', max_length=5, null=True)),
                ('vegetable', models.CharField(blank=True, default='no', max_length=5, null=True)),
                ('poultry', models.CharField(blank=True, default='no', max_length=5, null=True)),
                ('goat', models.CharField(blank=True, default='no', max_length=5, null=True)),
                ('fisheries', models.CharField(blank=True, default='no', max_length=5, null=True)),
                ('others', models.CharField(blank=True, default='no', max_length=5, null=True)),
                ('surplus', models.CharField(default='', max_length=50)),
                ('income', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('prodCompany', models.CharField(default='', max_length=50)),
                ('farmernum', models.IntegerField(blank=True, default='0', null=True)),
                ('innov_method', models.CharField(default='', max_length=150)),
                ('afif', models.CharField(blank=True, max_length=10, null=True)),
                ('ifAFIF', models.CharField(blank=True, max_length=10, null=True)),
                ('covervillage', models.IntegerField(blank=True, default='0', null=True)),
                ('averagehousehold', models.IntegerField(blank=True, default='0', null=True)),
                ('shg', models.IntegerField(blank=True, default='0', null=True)),
                ('lat', models.CharField(default='', max_length=15)),
                ('lng', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
