# Generated by Django 4.1.7 on 2023-03-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailF', models.CharField(max_length=100)),
                ('studentName', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=3)),
                ('collegeName', models.CharField(max_length=100)),
                ('websiteUsername', models.CharField(max_length=100)),
                ('sponsered', models.CharField(max_length=3)),
                ('sponsBy', models.CharField(max_length=100)),
                ('ownDevice', models.CharField(max_length=3)),
                ('date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'app_data_of_form',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='uploadwellpicturemodel',
            options={'managed': True},
        ),
    ]
